---
- name: C-bug
  color: "#ef4444"
- name: C-dependency
  color: "#f87171"
- name: C-documentation
  color: "#dc2626"
- name: C-feature-request
  color: "#fca5a5"
- name: L-github
  color: "#eab308"
- name: L-rust
  color: "#facc15"
- name: R-added
  color: "#64748b"
- name: R-changed
  color: "#94a3b8"
- name: R-deprecated
  color: "#475569"
- name: R-fixed
  color: "#cbd5e1"
- name: R-ignore
  color: "#334155"
- name: R-removed
  color: "#e2e8f0"
- name: R-security
  color: "#1e293b"
