- name: L-github
  color: "#fde047"
  description: An issue related to GitHub
- name: L-rust
  color: "#a16207"
  description: An issue related to Rust
- name: C-bug
  color: "#fecaca"
  description: Report a new bug
- name: C-dependency
  color: "#f87171"
  description: Change or update a dependency
- name: C-documentation
  color: "#dc2626"
  description: Improve the documentation
- name: C-feature-request
  color: "#991b1b"
  description: Request a new feature
- name: R-added
  color: "#f1f5f9"
  description: Add a new feature to the release notes
- name: R-changed
  color: "#e2e8f0"
  description: Add a change in existing functionality to the release notes
- name: R-deprecated
  color: "#94a3b8"
  description: Add a soon-to-be removed feature to the release notes
- name: R-fixed
  color: "#64748b"
  description: Add a fixed bug to the release notes
- name: R-ignore
  color: "#475569"
  description: Do not add this pull request to the release notes
- name: R-removed
  color: "#1e293b"
  description: Add a now removed feature to the release notes
- name: R-security
  color: "#0f172a"
  description: Add a vulnerability warning to the release notes
