[[group]]
colors = { fixed = "#4ade80" }
labels = ["good-first-issue"]

[[group]]
prefix = "C-"
colors = { tailwind = "red" }
labels = [
  { name = "bug", description = "Report a new bug" },
  { name = "dependency", description = "Change or update a dependency" },
  { name = "documentation", description = "Improve the documentation" },
  { name = "feature-request", description = "Request a new feature" },
]

[[group]]
prefix = "L-"
colors = { tailwind = "yellow" }
labels = [{ name = "rust", description = "An issue related to Rust" }]

[[group]]
prefix = "R-"
colors = { tailwind = "slate" }
labels = [
  { name = "added", description = "Add a new feature to the release notes" },
  { name = "changed", description = "Add a change in existing functionality to the release notes" },
  { name = "deprecated", description = "Add a soon-to-be removed feature to the release notes" },
  { name = "fixed", description = "Add a fixed bug to the release notes" },
  { name = "ignore", description = "Do not add this pull request to the release notes" },
  { name = "removed", description = "Add a now removed feature to the release notes" },
  { name = "security", description = "Add a vulnerability warning to the release notes" },
]

[[group]]
prefix = "T-"
colors = { tailwind = "blue" }
labels = [
  { name = "cli", description = "An issue related to the command-line interface" },
  { name = "github-action", description = "An issue related to the GitHub Action" },
]
