[categories]
prefix = "C-"
colors = { tailwind = "red" }
labels = ["bug", "dependency", "documentation", "feature-request"]

[ecosystems]
prefix = "L-"
colors = { tailwind = "yellow" }
labels = ["github", "rust"]

[releases]
prefix = "R-"
colors = { tailwind = "slate" }
labels = [
  "added",
  "changed",
  "deprecated",
  "fixed",
  "ignore",
  "removed",
  "security",
]
