---
name: GitHub

"on":
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/github.yml
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false

      - name: Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # 2.3.3
        with:
          config-file: .github/labels.yml
          dry-run: ${{ github.ref != 'refs/heads/main' }}
